### ISSUE TITLE
[Dart] Cant turn app on :(

### ISSUE THREAD

**Issue by MarekQX** [marceldev89/BattleNET#50]
Hello, iam unable to start the Dart after one of my saved servers was turned off :(
I dont know if it is connected to it somehow or not. I have reinstalled app multipletimes, but still not working... Please help me :(

---------- Info ----------
DaRT v2.2
Time of crash: 11/20/2023 3:43:17 AM
Total used memory: 22 MB / 8069 MB
Threads: 12
---------- Error ----------
Configuration system failed to initialize
---------- StackTrace ----------
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at DaRT.Properties.Settings.get_UpgradeConfig()
   at DaRT.GUImain..ctor(String version)
   at DaRT.Program.Main(String[] args)

**Comment by marceldev89** [comment]
@DomiStyle I told @MarekQX on Twitter he could use my issue tracker to try and get into contact with you as you archived your repo a while ago. I know nothing about Dart without going through the source code. 😅

@MarekQX judging by the error I'd say you're missing a config file maybe?

**Comment by griha41** [comment]
> Hello, iam unable to start the Dart after one of my saved servers was turned off :(
> I dont know if it is connected to it somehow or not. I have reinstalled app multipletimes, but still not working... Please help me :(
> 
> ---------- Info ----------
> DaRT v2.2
> Time of crash: 11/20/2023 3:43:17 AM
> Total used memory: 22 MB / 8069 MB
> Threads: 12
> ---------- Error ----------
> Configuration system failed to initialize
> ---------- StackTrace ----------
>    at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
>    at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
>    at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
>    at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
>    at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
>    at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
>    at System.Configuration.ConfigurationManager.GetSection(String sectionName)
>    at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
>    at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
>    at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
>    at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
>    at System.Configuration.SettingsBase.get_Item(String propertyName)
>    at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
>    at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
>    at DaRT.Properties.Settings.get_UpgradeConfig()
>    at DaRT.GUImain..ctor(String version)
>    at DaRT.Program.Main(String[] args)

Hello.
The first of all you shall try to make your database back up and start over app. If everything went fine you shall remove the new database file and edit the old one.

Possible problem is too 'fat' databases you shall optimize it and the second is that you database file was somehow corrupted.

The database file located at: "{DaRT_Tool_Path}\data\db\dart.db", it's SQLite Database v3 file, I suggest you to edit and open with through freeware app "DB Browser for SQLite", you may find it for windows and most of Linux distributions.
For performing the DB compression, open file -> Select SQL tab and input there the query: "vacuum;" and press "Play" button or F5 on keyboard. Task would be done if 2 - 3 minutes for tooo damn slow PC and it will optimize the size and DB performance!

Also based you exception log you've got the corrupted DaRT config file that tried to load but had an issue. It would be bit harder but not really disturbed enough.

First of all:
Find in the path: "{DaRT_Tool_Path}\DaRT.exe.config", rename it into the "DaRT.exe.config.BAK"
Then create the New Text File with name: "DaRT.exe.config" and insert there the next content:

[DaRT.exe.config,txt](https://github.com/marceldev89/BattleNET/files/13408236/DaRT.exe.config.txt)
P.S. Just rename it back to the "DaRT.exe.config", because the GitHub is not accept any file except the .txt!!

After you've done your job, please start over the DaRT - application shall be started. If it's not start over again and it will work. I hope that it helped to you enough to return it back online :D

**Comment by griha41** [comment]
> @DomiStyle I told @MarekQX on Twitter he could use my issue tracker to try and get into contact with you as you archived your repo a while ago. I know nothing about Dart without going through the source code. 😅
> 
> @MarekQX judging by the error I'd say you're missing a config file maybe?

DaRT - is an old Arma/DayZ (latest release was in 2012 year) and Battleye-based tool that used by many admins around the world. It's also used the @DomiStyle library for op with the Battleye protocol!
This tool is still alive, the devs for infistar returned it back with some features and called it as "BRC", you may find it on InfiSTAR site. There's a free and shareware versions (supports detection of SteamID64, detection Is IP using VPN and blah-blah-blah).

**Comment by MarekQX** [comment]
Thank you for help ideas.
1 - I have tried to empty the database, but its already empty, since i tried to completly remove dart from my pc and donwload it back from git. So not any changes there.

2 - Replacing content of config file also didnt helped.

Are there some files in computes, which are created by Dart when running app for first time ? (If yes, i didnt delete those, so maybe any issue there ?)

**Comment by griha41** [comment]
> Thank you for help ideas. 1 - I have tried to empty the database, but its already empty, since i tried to completly remove dart from my pc and donwload it back from git. So not any changes there.
> 
> 2 - Replacing content of config file also didnt helped.
> 
> Are there some files in computes, which are created by Dart when running app for first time ? (If yes, i didnt delete those, so maybe any issue there ?)

Sorry it was my misstake. Id' sented you the wrong CFG. Replace yours "{DaRT_Tool_Path}\DaRT.exe.config" with this one
[DaRT.exe.config.txt](https://github.com/marceldev89/BattleNET/files/13412083/DaRT.exe.config.txt)


But Don't forget to remove the .txt @ the end of "DaRT.exe.config.txt" it shall be "DaRT.exe.config"!

**Comment by MarekQX** [comment]
Even if iam trying to use your config, or config which is there on github as default, iam still having same crash of app after starting it. (And i need to close it trough task manager, button X for close will open it again with same issue againg and again)

File is config format, iam editing it with visual studio

**Comment by griha41** [comment]
> Even if iam trying to use your config, or config which is there on github as default, iam still having same crash of app after starting it. (And i need to close it trough task manager, button X for close will open it again with same issue againg and again)

That's quite odd i have latest Win10 and it starts quite fast no problems at all...

Get source & execs here https://github.com/DomiStyle/DaRT

**Comment by MarekQX** [comment]
There is no exe file, i will need to find a way how to build a solution of it since i currently dont have visual studio on my gaming pc.. Thanks

**Comment by griha41** [comment]
> There is no exe file, i will need to find a way how to build a solution of it since i currently dont have visual studio on my gaming pc.. Thanks

Get Visual Studio 2019 or 2022 and buidl it. It's free and not too hard.

Download, install, while installing select C# development. It will install all components, then open the project (DaRT.sln) and select Build -> Run. That's should be enough.
